cenarios:
- nome_cenario: previsao_ipca_arima
  serie_id: IPCA
  modelo: ARIMA
  parametros:
    p: 5
    d: 1
    q: 0
  horizonte_previsao: 12
  intervalo_confianca: 0.95
- nome_cenario: previsao_selic_prophet
  serie_id: SELIC
  modelo: Prophet
  parametros:
    growth: linear
    seasonality_mode: multiplicative
  horizonte_previsao: 24
  intervalo_confianca: 0.9
- nome_cenario: previsao_vendas_rf
  serie_id: VENDAS_MENSAIS
  modelo: RandomForest
  parametros:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  horizonte_previsao: 6
  intervalo_confianca: 0.95
- nome_cenario: PLOA
  serie_id: SELIC
  modelo: RandomForest
  horizonte_previsao: 1
  intervalo_confianca: 0.5
  parametros:
    n_estimators: 100
    max_depth: 10
    random_state: 42
