cenarios:
- nome_cenario: PrevisaoTR
  serie_id: tr_mensal
  modelo: RandomForest
  horizonte_previsao: 24
  intervalo_confianca: 1.0
  parametros:
    n_estimators: 100
    max_depth: 5
    random_state: 42
- nome_cenario: PrevisaoTR-2
  serie_id: tr_mensal
  modelo: ARIMA
  horizonte_previsao: 48
  intervalo_confianca: 1.0
  parametros:
    p: 3
    d: 1
    q: 1
- nome_cenario: Ptax-Dolar
  serie_id: dolar_mensal
  modelo: Prophet
  horizonte_previsao: 24
  intervalo_confianca: 0.5
  parametros: 
    growth: 'linear'
    seasonality_mode: 'multiplicative'
